/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'KWON' at '16. 10. 30 오후 7:27' with Gradle 2.14.1
 *
 * @author KWON, @date 16. 10. 30 오후 7:27
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
